---
AWSTemplateFormatVersion: "2010-09-09"
Description: Workshop Github Actions - OIDC IDP and associated Role for Full CI/CD

Parameters:

  GitHubOrganization:
    Type: String
    Description: This is the root organization or personal account where repos are stored (Case Sensitive)
    Default: ""

  RepositoryName:
    Type: String
    Description: The repo(s) these roles will have access to. (Use * for all org or personal repos)
    Default: "*"

  BranchName:
    Type: String
    Description: Name of the git branch to to trust. (Use * for all branches)
    Default: "*"

  RoleName:
    Type: String
    Description: Name the Role
    Default: ""

Resources:

  IdpGitHubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Tags:
        - Key: Name
          Value: !Sub ${RoleName}-OIDC-Provider

  RoleGithubActions:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${RoleName}-GA
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref IdpGitHubOidc
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: "sts.amazonaws.com"
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrganization}/${RepositoryName}:${BranchName}
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess

Outputs:

  IdpGitHubOidc:
    Description: "ARN of Github OIDC Provider"
    Value: !GetAtt IdpGitHubOidc.Arn

  RoleGithubActionsARN:
    Description: "ARN of Read Only Access Role for GitHub Actions"
    Value: !GetAtt RoleGithubActions.Arn