name: 'sast'

## run ci testing on all push events
on: [push]

jobs:
  ## Guard rule set
  sast-guard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: grolston/guard-action@main
      with:
        data_directory: './cloudformation/' ## change to your template directory
        rule_set: "NIST800-53Rev5"
        show_summary: 'none'
        output_format: 'json'
